void sendCSS(WiFiClient client)
{
client.println(
// ------------------- BUTTONS -------------------
".menu_button {\r\n"
"width: 100%;\r\n"
"height: 50px;\r\n"
"border-radius: 8px;\r\n"
"text-align: center;\r\n"
"cursor: pointer;\r\n"
"display: block;\r\n"
"margin-bottom: 12px;\r\n"
"font: 14px/50px 'Segoe UI', Tahoma, sans-serif;\r\n"
"transition: all 0.3s ease;\r\n"
"border: 1px solid #4a90e2;\r\n"
"background: linear-gradient(135deg, #ffffff 0%, #f8fbfd 100%);\r\n"
"color: #1e3a5f;\r\n"
"box-shadow: 0 2px 8px rgba(74, 144, 226, 0.15);\r\n"
"font-weight: 500;\r\n"
"}\r\n"
".menu_button:hover {\r\n"
"background: linear-gradient(135deg, #4a90e2 0%, #357abd 100%);\r\n"
"color: white;\r\n"
"transform: translateY(-2px);\r\n"
"box-shadow: 0 4px 15px rgba(74, 144, 226, 0.3);\r\n"
"border-color: #357abd;\r\n"
"}\r\n"
".menu_button:active {\r\n"
"transform: translateY(0);\r\n"
"}\r\n"
// ------------------- HIDDEN INPUT -------------------
".hidden_input {\r\n"
"width: 0.1px;\r\n"
"height: 0.1px;\r\n"
"opacity: 0;\r\n"
"overflow: hidden;\r\n"
"position: absolute;\r\n"
"z-index: -1;\r\n"
"}\r\n"
// ------------------- IMAGE BOX -------------------
".imgBox {\r\n"
"border: 2px dashed #4a90e2;\r\n"
"border-radius: 12px;\r\n"
"background: #f8fbfd;\r\n"
"background-repeat: no-repeat;\r\n"
"text-align: center;\r\n"
"margin-top: 10px;\r\n"
"padding: 20px;\r\n"
"transition: all 0.3s ease;\r\n"
"}\r\n"
".imgBox:hover {\r\n"
"border-color: #357abd;\r\n"
"background: #ffffff;\r\n"
"box-shadow: 0 4px 20px rgba(74, 144, 226, 0.15);\r\n"
"}\r\n"
".mesBox {\r\n"
"margin: 80px 60px;\r\n"
"color: #4a90e2;\r\n"
"font-size: 18px;\r\n"
"font-family: 'Segoe UI', Verdana, Arial, sans-serif;\r\n"
"opacity: 0.8;\r\n"
"font-weight: 500;\r\n"
"}\r\n"
// ------------------- BACKGROUND PANELS -------------------
".header_back {\r\n"
"width: 100%;\r\n"
"height: 100px;\r\n"
"background: linear-gradient(135deg, #4a90e2 0%, #5fa3e8 100%);\r\n"
"box-shadow: 0 2px 10px rgba(74, 144, 226, 0.2);\r\n"
"}\r\n"
".content_back {\r\n"
"width: 100%;\r\n"
"background: #e8f4f8;\r\n"
"min-height: calc(100vh - 200px);\r\n"
"}\r\n"
".footer_back {\r\n"
"width: 100%;\r\n"
"height: 100px;\r\n"
"background: linear-gradient(135deg, #4a90e2 0%, #5fa3e8 100%);\r\n"
"box-shadow: 0 -2px 10px rgba(74, 144, 226, 0.2);\r\n"
"}\r\n"
// ------------------- INNER PANELS -------------------
".header_face {\r\n"
"width: 1024px;\r\n"
"height: 100px;\r\n"
"margin: 0 auto;\r\n"
"background: linear-gradient(135deg, #5fa3e8 0%, #7bb5ee 100%);\r\n"
"border-bottom: 2px solid #ffffff;\r\n"
"display: flex;\r\n"
"align-items: center;\r\n"
"padding: 0 30px;\r\n"
"}\r\n"
".content_face {\r\n"
"width: 1024px;\r\n"
"height: 100%;\r\n"
"margin: 0 auto;\r\n"
"background: linear-gradient(135deg, #ffffff 0%, #f8fbfd 100%);\r\n"
"box-shadow: 0 0 30px rgba(74, 144, 226, 0.15);\r\n"
"border-radius: 8px;\r\n"
"}\r\n"
".footer_face {\r\n"
"width: 1024px;\r\n"
"height: 100%;\r\n"
"margin: 0 auto;\r\n"
"background: linear-gradient(135deg, #5fa3e8 0%, #7bb5ee 100%);\r\n"
"border-top: 2px solid #ffffff;\r\n"
"display: flex;\r\n"
"align-items: center;\r\n"
"padding: 0 30px;\r\n"
"color: #ffffff;\r\n"
"}\r\n"
// ------------------- MENU BAR -------------------
".menu_bar {\r\n"
"border-right: 1px solid #d6e9f8;\r\n"
"background: linear-gradient(180deg, #f8fbfd 0%, #ffffff 100%);\r\n"
"vertical-align: top;\r\n"
"padding: 20px;\r\n"
"width: 220px;\r\n"
"height: 100%;\r\n"
"}\r\n"
// ------------------- CONTENT BODY -------------------
".content_body {\r\n"
"vertical-align: top;\r\n"
"text-align: center;\r\n"
"height: 100%;\r\n"
"padding: 30px;\r\n"
"padding-left: 15px;\r\n"
"background: linear-gradient(135deg, #ffffff 0%, #f8fbfd 100%);\r\n"
"}\r\n"
// ------------------- TITLES & TEXT -------------------
".title {\r\n"
"color: #1e3a5f;\r\n"
"font-size: 28px;\r\n"
"font-family: 'Segoe UI', Arial, sans-serif;\r\n"
"font-weight: 600;\r\n"
"letter-spacing: -0.3px;\r\n"
"text-shadow: 0 2px 10px rgba(0,0,0,0.05);\r\n"
"}\r\n"
".comment {\r\n"
"width: 100%;\r\n"
"color: #4a90e2;\r\n"
"font-size: 14px;\r\n"
"font-style: normal;\r\n"
"font-family: 'Segoe UI', Arial, sans-serif;\r\n"
"text-align: center;\r\n"
"font-weight: 500;\r\n"
"}\r\n"
// ------------------- NUMERIC INPUT -------------------
".nud {\r\n"
"width: 70px;\r\n"
"border: 1px solid #b8d4e8;\r\n"
"border-radius: 6px;\r\n"
"padding: 8px;\r\n"
"background: #f8fbfd;\r\n"
"color: #1e3a5f;\r\n"
"font-family: 'Segoe UI', monospace;\r\n"
"transition: border-color 0.3s ease;\r\n"
"}\r\n"
".nud:focus {\r\n"
"outline: none;\r\n"
"border-color: #4a90e2;\r\n"
"box-shadow: 0 0 0 3px rgba(74, 144, 226, 0.1);\r\n"
"background: #ffffff;\r\n"
"}\r\n"
);
}

//void sendCSS(WiFiClient client)
//{
//client.println(
//// ------------------- BUTTONS -------------------
//".menu_button {\r\n"
//"width: 100%;\r\n"
//"height: 50px;\r\n"
//"border-radius: 8px;\r\n"
//"text-align: center;\r\n"
//"cursor: pointer;\r\n"
//"display: block;\r\n"
//"margin-bottom: 12px;\r\n"
//"font: 14px/50px 'Segoe UI', Tahoma, sans-serif;\r\n"
//"transition: all 0.3s ease;\r\n"
//"border: 1px solid #1976d2;\r\n"
//"background: linear-gradient(135deg, #1565c0 0%, #0d47a1 100%);\r\n"
//"color: #e3f2fd;\r\n"
//"box-shadow: 0 2px 8px rgba(13, 71, 161, 0.3);\r\n"
//"font-weight: 500;\r\n"
//"}\r\n"
//".menu_button:hover {\r\n"
//"background: linear-gradient(135deg, #1976d2 0%, #1565c0 100%);\r\n"
//"color: white;\r\n"
//"transform: translateY(-2px);\r\n"
//"box-shadow: 0 4px 15px rgba(25, 118, 210, 0.5);\r\n"
//"border-color: #42a5f5;\r\n"
//"}\r\n"
//".menu_button:active {\r\n"
//"transform: translateY(0);\r\n"
//"}\r\n"
//// ------------------- HIDDEN INPUT -------------------
//".hidden_input {\r\n"
//"width: 0.1px;\r\n"
//"height: 0.1px;\r\n"
//"opacity: 0;\r\n"
//"overflow: hidden;\r\n"
//"position: absolute;\r\n"
//"z-index: -1;\r\n"
//"}\r\n"
//// ------------------- IMAGE BOX -------------------
//".imgBox {\r\n"
//"border: 2px dashed #42a5f5;\r\n"
//"border-radius: 12px;\r\n"
//"background: #0d47a1;\r\n"
//"background-repeat: no-repeat;\r\n"
//"text-align: center;\r\n"
//"margin-top: 10px;\r\n"
//"padding: 20px;\r\n"
//"transition: all 0.3s ease;\r\n"
//"}\r\n"
//".imgBox:hover {\r\n"
//"border-color: #64b5f6;\r\n"
//"background: #1565c0;\r\n"
//"box-shadow: 0 4px 20px rgba(66, 165, 245, 0.2);\r\n"
//"}\r\n"
//".mesBox {\r\n"
//"margin: 80px 60px;\r\n"
//"color: #90caf9;\r\n"
//"font-size: 18px;\r\n"
//"font-family: 'Segoe UI', Verdana, Arial, sans-serif;\r\n"
//"opacity: 0.8;\r\n"
//"font-weight: 500;\r\n"
//"}\r\n"
//// ------------------- BACKGROUND PANELS -------------------
//".header_back {\r\n"
//"width: 100%;\r\n"
//"height: 100px;\r\n"
//"background: linear-gradient(135deg, #0d47a1 0%, #1565c0 100%);\r\n"
//"box-shadow: 0 2px 10px rgba(13, 71, 161, 0.4);\r\n"
//"}\r\n"
//".content_back {\r\n"
//"width: 100%;\r\n"
//"background: #0a1929;\r\n"
//"min-height: calc(100vh - 200px);\r\n"
//"}\r\n"
//".footer_back {\r\n"
//"width: 100%;\r\n"
//"height: 100px;\r\n"
//"background: linear-gradient(135deg, #0d47a1 0%, #1565c0 100%);\r\n"
//"box-shadow: 0 -2px 10px rgba(13, 71, 161, 0.4);\r\n"
//"}\r\n"
//// ------------------- INNER PANELS -------------------
//".header_face {\r\n"
//"width: 1024px;\r\n"
//"height: 100px;\r\n"
//"margin: 0 auto;\r\n"
//"background: linear-gradient(135deg, #1565c0 0%, #1976d2 100%);\r\n"
//"border-bottom: 2px solid #42a5f5;\r\n"
//"display: flex;\r\n"
//"align-items: center;\r\n"
//"padding: 0 30px;\r\n"
//"}\r\n"
//".content_face {\r\n"
//"width: 1024px;\r\n"
//"height: 100%;\r\n"
//"margin: 0 auto;\r\n"
//"background: linear-gradient(135deg, #0d47a1 0%, #1565c0 100%);\r\n"
//"box-shadow: 0 0 30px rgba(13, 71, 161, 0.5);\r\n"
//"border-radius: 8px;\r\n"
//"}\r\n"
//".footer_face {\r\n"
//"width: 1024px;\r\n"
//"height: 100%;\r\n"
//"margin: 0 auto;\r\n"
//"background: linear-gradient(135deg, #1565c0 0%, #1976d2 100%);\r\n"
//"border-top: 2px solid #42a5f5;\r\n"
//"display: flex;\r\n"
//"align-items: center;\r\n"
//"padding: 0 30px;\r\n"
//"color: #90caf9;\r\n"
//"}\r\n"
//// ------------------- MENU BAR -------------------
//".menu_bar {\r\n"
//"border-right: 1px solid #1976d2;\r\n"
//"background: linear-gradient(180deg, #0d47a1 0%, #1a237e 100%);\r\n"
//"vertical-align: top;\r\n"
//"padding: 20px;\r\n"
//"width: 220px;\r\n"
//"height: 100%;\r\n"
//"}\r\n"
//// ------------------- CONTENT BODY -------------------
//".content_body {\r\n"
//"vertical-align: top;\r\n"
//"text-align: center;\r\n"
//"height: 100%;\r\n"
//"padding: 30px;\r\n"
//"padding-left: 15px;\r\n"
//"background: linear-gradient(135deg, #0d47a1 0%, #1565c0 100%);\r\n"
//"}\r\n"
//// ------------------- TITLES & TEXT -------------------
//".title {\r\n"
//"color: #ffffff;\r\n"
//"font-size: 28px;\r\n"
//"font-family: 'Segoe UI', Arial, sans-serif;\r\n"
//"font-weight: 600;\r\n"
//"letter-spacing: -0.3px;\r\n"
//"text-shadow: 0 2px 10px rgba(0,0,0,0.2);\r\n"
//"}\r\n"
//".comment {\r\n"
//"width: 100%;\r\n"
//"color: #90caf9;\r\n"
//"font-size: 14px;\r\n"
//"font-style: normal;\r\n"
//"font-family: 'Segoe UI', Arial, sans-serif;\r\n"
//"text-align: center;\r\n"
//"font-weight: 500;\r\n"
//"}\r\n"
//// ------------------- NUMERIC INPUT -------------------
//".nud {\r\n"
//"width: 70px;\r\n"
//"border: 1px solid #1976d2;\r\n"
//"border-radius: 6px;\r\n"
//"padding: 8px;\r\n"
//"background: #0d47a1;\r\n"
//"color: #e3f2fd;\r\n"
//"font-family: 'Segoe UI', monospace;\r\n"
//"transition: border-color 0.3s ease;\r\n"
//"}\r\n"
//".nud:focus {\r\n"
//"outline: none;\r\n"
//"border-color: #42a5f5;\r\n"
//"box-shadow: 0 0 0 3px rgba(66, 165, 245, 0.2);\r\n"
//"}\r\n"
//);
//}
//
////
////void sendCSS(WiFiClient client)
////{
////client.println(
////
/////* ---------------- BLUE–WHITE PROFESSIONAL THEME ---------------- */
////
////".menu_button {\r\n"
////"width: 100%;\r\n"
////"height: 50px;\r\n"
////"border-radius: 4px;\r\n"
////"text-align: center;\r\n"
////"cursor: pointer;\r\n"
////"display: block;\r\n"
////"margin-bottom:5px;\r\n"
////"font: 14px/50px Tahoma;\r\n"
////"transition: all 0.18s ease-in-out;\r\n"
////"border: 1px solid #1E64C8;\r\n"
////"background: linear-gradient(to top right, #2D7FF0, #68A9FF 20%, rgba(255, 255, 255, 0) 80%, rgba(255, 255, 255, 0)) top right/500% 500%;\r\n"
////"color: #0A3A75;\r\n"
////"}\r\n"
////
////".menu_button:hover {\r\n"
////"color: white;\r\n"
////"background-position: bottom left;\r\n"
////"}\r\n"
////
////".hidden_input {\r\n"
////"width: 0.1px;\r\n"
////"height: 0.1px;\r\n"
////"opacity: 0;\r\n"
////"overflow: hidden;\r\n"
////"position: absolute;\r\n"
////"z-index: -1;\r\n"
////"}\r\n"
////
////".imgBox\r\n"
////"{\r\n"
////"border: 2px dashed #1E64C8;\r\n"
////"border-radius: 8px;\r\n"
////"background: #F5F9FF;\r\n"
////"background-repeat: no-repeat;\r\n"
////"text-align: center;\r\n"
////"margin-top:10px;\r\n"
////"}\r\n"
////
////".mesBox {\r\n"
////"margin: 100px 70px;\r\n"
////"color: #1E64C8;\r\n"
////"font-size: 25px;\r\n"
////"font-family: Verdana, Arial, sans-serif;\r\n"
////"}\r\n"
////
////".header_back\r\n"
////"{\r\n"
////"width:100%;\r\n"
////"height:100px;\r\n"
////"background:#E8F1FF;\r\n"
////"}\r\n"
////
////".content_back\r\n"
////"{\r\n"
////"width:100%;\r\n"
////"background:#E8F1FF;\r\n"
////"}\r\n"
////
////".footer_back\r\n"
////"{\r\n"
////"width:100%;\r\n"
////"height:100px;\r\n"
////"background:#E8F1FF;\r\n"
////"}\r\n"
////
////".header_face\r\n"
////"{\r\n"
////"width:1024px;\r\n"
////"height:100px;\r\n"
////"margin:0 auto;\r\n"
////"background:#D6E8FF;\r\n"
////"}\r\n"
////
////".content_face\r\n"
////"{\r\n"
////"width:1024px;\r\n"
////"height:100%;\r\n"
////"margin:0 auto;\r\n"
////"background:#FFFFFF;\r\n"
////"}\r\n"
////
////".footer_face\r\n"
////"{\r\n"
////"width:1024px;\r\n"
////"height:100%;\r\n"
////"margin:0 auto;\r\n"
////"background:#D6E8FF;\r\n"
////"}\r\n"
////
////".menu_bar\r\n"
////"{\r\n"
////"border-right:1px solid #1E64C8;\r\n"
////"background:#F0F6FF;\r\n"
////"vertical-align:top;\r\n"
////"padding:15px;\r\n"
////"width:200px;\r\n"
////"height:100%\r\n"
////"}\r\n"
////
////".content_body\r\n"
////"{\r\n"
////"vertical-align:top;\r\n"
////"text-align:center;\r\n"
////"height:100%;\r\n"
////"padding:30px;\r\n"
////"padding-left:15px;\r\n"
////"}\r\n"
////
////".title\r\n"
////"{\r\n"
////"color:#1E64C8;\r\n"
////"font-size:32px;\r\n"
////"font-family: arial;\r\n"
////"}\r\n"
////
////".comment\r\n"
////"{\r\n"
////"width:100%;\r\n"
////"color:#1E64C8;\r\n"
////"font-size:16px;\r\n"
////"font-style:italic;\r\n"
////"font-family: arial;\r\n"
////"text-align:center;\r\n"
////"}\r\n"
////
////".nud\r\n"
////"{\r\n"
////"width:70px;\r\n"
////"}\r\n"
////
////);
////}
////
