void sendHtml(WiFiClient client, IPAddress myIP)
{
client.print(
"<!DOCTYPE html>\r\n"
"<html>\r\n"
"<head>\r\n"
"<meta charset='utf-8'>\r\n"
"<title>Excellent Solutions</title>\r\n"
"<link rel='icon' href='data:;base64,='>\r\n"
"<link rel='stylesheet' href='styles.css'>\r\n"
"<script src='scriptA.js'></script>\r\n"
"<script src='scriptB.js'></script>\r\n"
"<script src='scriptC.js'></script>\r\n"
"<script src='scriptD.js'></script>\r\n"

"<style>\r\n"
"body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin:0; padding:0; background:#e8f4f8; color:#1e3a5f; }\r\n"

/* =============== WELCOME PAGE =============== */
".welcome_page { display:flex; flex-direction:column; align-items:center; justify-content:center; height:100vh; background: linear-gradient(135deg, #4a90e2 0%, #5fa3e8 50%, #7bb5ee 100%); position:relative; overflow:hidden; }\r\n"
".welcome_page::before { content:''; position:absolute; width:500px; height:500px; background:rgba(255,255,255,0.1); border-radius:50%; top:-100px; right:-100px; }\r\n"
".welcome_page::after { content:''; position:absolute; width:400px; height:400px; background:rgba(255,255,255,0.08); border-radius:50%; bottom:-150px; left:-100px; }\r\n"
".welcome_content { z-index:10; text-align:center; }\r\n"
".welcome_title { font-size:52px; font-weight:700; margin-bottom:20px; color:#ffffff; text-shadow: 0 4px 30px rgba(0,0,0,0.3); letter-spacing: -1px; animation: fadeInDown 0.8s ease; }\r\n"
".welcome_subtitle { font-size:20px; color:#bbdefb; margin-bottom:40px; font-weight:300; letter-spacing:1px; animation: fadeInUp 0.8s ease 0.2s both; }\r\n"
".welcome_icon { font-size:80px; margin-bottom:30px; animation: bounceIn 1s ease 0.4s both; }\r\n"
"@keyframes fadeInDown { from { opacity:0; transform:translateY(-30px); } to { opacity:1; transform:translateY(0); } }\r\n"
"@keyframes fadeInUp { from { opacity:0; transform:translateY(30px); } to { opacity:1; transform:translateY(0); } }\r\n"
"@keyframes bounceIn { 0% { opacity:0; transform:scale(0.3); } 50% { opacity:1; transform:scale(1.05); } 70% { transform:scale(0.9); } 100% { transform:scale(1); } }\r\n"

/* =============== LOGIN PAGE =============== */
".login_page { display:flex; flex-direction:column; align-items:center; justify-content:center; height:100vh; background: linear-gradient(135deg, #0d47a1 0%, #1565c0 100%); }\r\n"
".login_box { background:#1a237e; padding:40px; border-radius:16px; width:320px; box-shadow:0 8px 32px rgba(0,0,0,0.3); border:1px solid #283593; }\r\n"
".hidden { display:none; }\r\n"
".btn { padding:14px 28px; border:none; border-radius:8px; cursor:pointer; background: linear-gradient(135deg, #1976d2 0%, #1565c0 100%); color:white; font-weight:600; font-size:16px; transition: all 0.3s ease; box-shadow: 0 4px 15px rgba(25, 118, 210, 0.4); animation: fadeInUp 0.8s ease 0.6s both; }\r\n"
".btn:hover { background: linear-gradient(135deg, #1565c0 0%, #0d47a1 100%); transform: translateY(-2px); box-shadow: 0 6px 20px rgba(25, 118, 210, 0.5); }\r\n"
".btn:active { transform: translateY(0); }\r\n"
"select, input { border:1px solid #283593; border-radius:8px; background:#0d47a1; color:#e3f2fd; padding:12px; font-size:14px; transition: all 0.3s ease; }\r\n"
"select:focus, input:focus { outline:none; border-color:#42a5f5; box-shadow: 0 0 0 3px rgba(66, 165, 245, 0.1); }\r\n"

/* =============== ADMIN PANEL =============== */
".admin_container { padding:40px; background: linear-gradient(135deg, #0a1929 0%, #0d47a1 100%); min-height:100vh; }\r\n"
".admin_header { margin-bottom:40px; }\r\n"
".admin_title { color:#ffffff; font-size:36px; margin-bottom:10px; font-weight:700; }\r\n"
".admin_subtitle { color:#90caf9; font-size:16px; font-weight:400; }\r\n"
".stats_grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(250px, 1fr)); gap:24px; margin-bottom:40px; }\r\n"
".stat_card { background: linear-gradient(135deg, #1565c0 0%, #0d47a1 100%); padding:24px; border-radius:12px; box-shadow:0 4px 20px rgba(0,0,0,0.2); border:1px solid #1976d2; cursor:pointer; transition: all 0.3s ease; }\r\n"
".stat_card:hover { transform: translateY(-5px); box-shadow:0 8px 30px rgba(25, 118, 210, 0.4); border-color:#42a5f5; }\r\n"
".stat_icon { font-size:36px; margin-bottom:12px; }\r\n"
".stat_value { font-size:32px; font-weight:700; color:#ffffff; margin-bottom:8px; }\r\n"
".stat_label { font-size:14px; color:#90caf9; text-transform:uppercase; letter-spacing:1px; }\r\n"

/* =============== HISTORY SECTION =============== */
".historyBox { background: linear-gradient(135deg, #1a237e 0%, #0d47a1 100%); border:1px solid #283593; border-radius:12px; padding:30px; box-shadow:0 4px 20px rgba(0,0,0,0.2); }\r\n"
".histTitle { font-size:24px; font-weight:600; color:#ffffff; margin-bottom:24px; border-bottom:2px solid #1976d2; padding-bottom:12px; }\r\n"
".history_grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(300px, 1fr)); gap:20px; }\r\n"
".histCard { background:#0d47a1; padding:20px; border-radius:10px; border:1px solid #1565c0; cursor:pointer; transition: all 0.3s ease; box-shadow:0 2px 10px rgba(0,0,0,0.15); }\r\n"
".histCard:hover { transform: translateY(-3px); box-shadow:0 6px 25px rgba(25, 118, 210, 0.3); border-color:#42a5f5; background:#1565c0; }\r\n"
".histDevice { font-size:18px; font-weight:600; color:#ffffff; margin-bottom:8px; }\r\n"
".histDate { font-size:13px; color:#90caf9; margin-bottom:10px; }\r\n"
".histDesc { font-size:14px; color:#bbdefb; line-height:1.5; }\r\n"

/* =============== OPERATOR PAGE =============== */
".header_back, .footer_back { background: linear-gradient(135deg, #0d47a1 0%, #1565c0 100%); }\r\n"
".content_back { background:#0a1929; }\r\n"
".title { color:#ffffff; font-weight:600; }\r\n"
".comment { color:#90caf9; font-weight:500; }\r\n"
"label { color:#90caf9; font-size:13px; font-weight:500; text-transform:uppercase; letter-spacing:0.5px; }\r\n"
"h3 { margin-top:0; }\r\n"
"</style>\r\n"

"<script>\r\n"
"function goToLogin(){ document.getElementById('welcome').classList.add('hidden'); document.getElementById('login').classList.remove('hidden'); }\r\n"

"function loginSubmit(){\r\n"
"  var role = document.getElementById('role').value;\r\n"
"  var pass = document.getElementById('password').value;\r\n"
"  if(role==='admin' && pass==='admin123'){\r\n"
"     document.getElementById('login').classList.add('hidden');\r\n"
"     document.getElementById('adminPanel').classList.remove('hidden');\r\n"
"  }\r\n"
"  else if(role==='operator' && pass==='operator123'){\r\n"
"     document.getElementById('login').classList.add('hidden');\r\n"
"     document.getElementById('operatorPage').classList.remove('hidden');\r\n"
"  }\r\n"
"  else{ alert('Invalid Credentials'); }\r\n"
"}\r\n"
"</script>\r\n"

"</head>\r\n"
"<body>\r\n"

/* ------------------------ WELCOME PAGE ------------------------ */
"<div id='welcome' class='welcome_page'>\r\n"
"<div class='welcome_content'>\r\n"
"<div class='welcome_icon'>🔷</div>\r\n"
"<div class='welcome_title'>Excellent Solutions</div>\r\n"
"<div class='welcome_subtitle'>Professional Device Management System</div>\r\n"
"<button class='btn' onclick='goToLogin()'>Get Started</button>\r\n"
"</div>\r\n"
"</div>\r\n"

/* ------------------------ LOGIN PAGE ------------------------ */
"<div id='login' class='login_page hidden'>\r\n"
"<div class='login_box'>\r\n"
"<h3 style='text-align:center; color:#ffffff; font-size:26px; margin-bottom:30px;'>Sign In</h3>\r\n"
"<label>Role:</label>\r\n"
"<select id='role' style='width:100%; margin-top:8px;'>\r\n"
"<option value='operator'>Operator</option>\r\n"
"<option value='admin'>Admin</option>\r\n"
"</select><br><br>\r\n"

"<label>Password:</label>\r\n"
"<input id='password' type='password' style='width:100%; margin-top:8px;'><br><br><br>\r\n"

"<button class='btn' style='width:100%;' onclick='loginSubmit()'>Login</button>\r\n"
"</div>\r\n"
"</div>\r\n"

/* ------------------------ ADMIN PANEL ------------------------ */
"<div id='adminPanel' class='hidden admin_container'>\r\n"
"<div class='admin_header'>\r\n"
"<div class='admin_title'>Admin Dashboard</div>\r\n"
"<div class='admin_subtitle'>Complete system overview and management</div>\r\n"
"</div>\r\n"

/* Stats Cards Grid */
"<div class='stats_grid'>\r\n"
"<div class='stat_card'>\r\n"
"<div class='stat_icon'>📊</div>\r\n"
"<div class='stat_value'>24</div>\r\n"
"<div class='stat_label'>Active Devices</div>\r\n"
"</div>\r\n"
"<div class='stat_card'>\r\n"
"<div class='stat_icon'>📁</div>\r\n"
"<div class='stat_value'>156</div>\r\n"
"<div class='stat_label'>Total Uploads</div>\r\n"
"</div>\r\n"
"<div class='stat_card'>\r\n"
"<div class='stat_icon'>👥</div>\r\n"
"<div class='stat_value'>8</div>\r\n"
"<div class='stat_label'>Active Users</div>\r\n"
"</div>\r\n"
"<div class='stat_card'>\r\n"
"<div class='stat_icon'>⚙️</div>\r\n"
"<div class='stat_value'>99.8%</div>\r\n"
"<div class='stat_label'>System Uptime</div>\r\n"
"</div>\r\n"
"</div>\r\n"

/* History Section with Cards */
"<div class='historyBox'>\r\n"
"<div class='histTitle'>📋 Recent Activity History</div>\r\n"
"<div class='history_grid'>\r\n"

"<div class='histCard'>\r\n"
"<div class='histDevice'>Device A1</div>\r\n"
"<div class='histDate'>📅 November 21, 2025</div>\r\n"
"<div class='histDesc'>Image updated — Face alignment corrected</div>\r\n"
"</div>\r\n"

"<div class='histCard'>\r\n"
"<div class='histDevice'>Device B7</div>\r\n"
"<div class='histDate'>📅 November 18, 2025</div>\r\n"
"<div class='histDesc'>Uploaded new template — Contrast enhanced</div>\r\n"
"</div>\r\n"

"<div class='histCard'>\r\n"
"<div class='histDevice'>Device C3</div>\r\n"
"<div class='histDate'>📅 November 15, 2025</div>\r\n"
"<div class='histDesc'>Operator replaced image — Resolution improved</div>\r\n"
"</div>\r\n"

"<div class='histCard'>\r\n"
"<div class='histDevice'>Device A1</div>\r\n"
"<div class='histDate'>📅 November 5, 2025</div>\r\n"
"<div class='histDesc'>Cropping parameters updated</div>\r\n"
"</div>\r\n"

"<div class='histCard'>\r\n"
"<div class='histDevice'>Device D2</div>\r\n"
"<div class='histDate'>📅 November 1, 2025</div>\r\n"
"<div class='histDesc'>New logo overlay added</div>\r\n"
"</div>\r\n"

"</div>\r\n"
"</div>\r\n"

"</div>\r\n"

/* ------------------------ ORIGINAL OPERATOR PAGE ------------------------ */
"<div id='operatorPage' class='hidden'>\r\n"
"<div class='header_back'>\r\n"
"<div class='header_face'></div>\r\n"
"</div>\r\n"
"<div class='content_back'>\r\n"
"<div class='content_face'>\r\n"
"<table style='width:100%; height:100%' border='0' cellspacing='0'>\r\n"
"<tr>\r\n"
"<td class='menu_bar' rowspan='2'>\r\n"
"<div id='BT'></div>\r\n"
"<table>\r\n"
"<tr>\r\n"
"<td class='comment' colspan='4'><br>Device IP:</td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td colspan='4'><input id='ip_addr' style='width:100%;text-align:center' type='text' value='" +
String(myIP[0]) + "." + String(myIP[1]) + "." + String(myIP[2]) + "." + String(myIP[3]) +
"'></td>\r\n"
"</tr>\r\n"
"<tr><td class='comment' colspan='4'><br>Bounds:</td></tr>\r\n"
"<tr id='XY'></tr>\r\n"
"<tr id='WH'></tr>\r\n"
"</table>\r\n"
"<div id='RB'></div>\r\n"
"</td>\r\n"

"<td class='content_body'>\r\n"
"<span class='title'>Original image</span><br>\r\n"
"<canvas id='source' class='hidden_input'></canvas>\r\n"
"<div id='srcBox'>\r\n"
"<div class='imgBox'>\r\n"
"<div class='mesBox'>Drop image here...</div>\r\n"
"</div>\r\n"
"</div>\r\n"
"</td>\r\n"
"</tr>\r\n"

"<tr>\r\n"
"<td id='dstBox' class='content_body'>\r\n"
"</td>\r\n"
"</tr>\r\n"

"</table>\r\n"
"</div>\r\n"
"</div>\r\n"

"<div class='footer_back'>\r\n"
"<div class='footer_face' id='logTag'>\r\n"
"</div>\r\n"
"</div>\r\n"
"</div>\r\n"

"</body>\r\n"
"</html>\r\n"
);
}

//void sendHtml(WiFiClient client, IPAddress myIP)
//{
//client.print(
//"<!DOCTYPE html>\r\n"
//"<html>\r\n"
//"<head>\r\n"
//"<meta charset='utf-8'>\r\n"
//"<title>Excellent Solutions</title>\r\n"
//"<link rel='icon' href='data:;base64,='>\r\n"
//"<link rel='stylesheet' href='styles.css'>\r\n"
//"<script src='scriptA.js'></script>\r\n"
//"<script src='scriptB.js'></script>\r\n"
//"<script src='scriptC.js'></script>\r\n"
//"<script src='scriptD.js'></script>\r\n"
//
//"<style>\r\n"
//"body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin:0; padding:0; background:#0a1929; color:#e3f2fd; }\r\n"
//
///* =============== WELCOME PAGE =============== */
//".welcome_page { display:flex; flex-direction:column; align-items:center; justify-content:center; height:100vh; background: linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%); position:relative; overflow:hidden; }\r\n"
//".welcome_page::before { content:''; position:absolute; width:500px; height:500px; background:rgba(255,255,255,0.1); border-radius:50%; top:-100px; right:-100px; }\r\n"
//".welcome_page::after { content:''; position:absolute; width:400px; height:400px; background:rgba(255,255,255,0.08); border-radius:50%; bottom:-150px; left:-100px; }\r\n"
//".welcome_content { z-index:10; text-align:center; }\r\n"
//".welcome_title { font-size:52px; font-weight:700; margin-bottom:20px; color:#ffffff; text-shadow: 0 4px 30px rgba(0,0,0,0.3); letter-spacing: -1px; animation: fadeInDown 0.8s ease; }\r\n"
//".welcome_subtitle { font-size:20px; color:#bbdefb; margin-bottom:40px; font-weight:300; letter-spacing:1px; animation: fadeInUp 0.8s ease 0.2s both; }\r\n"
//".welcome_icon { font-size:80px; margin-bottom:30px; animation: bounceIn 1s ease 0.4s both; }\r\n"
//"@keyframes fadeInDown { from { opacity:0; transform:translateY(-30px); } to { opacity:1; transform:translateY(0); } }\r\n"
//"@keyframes fadeInUp { from { opacity:0; transform:translateY(30px); } to { opacity:1; transform:translateY(0); } }\r\n"
//"@keyframes bounceIn { 0% { opacity:0; transform:scale(0.3); } 50% { opacity:1; transform:scale(1.05); } 70% { transform:scale(0.9); } 100% { transform:scale(1); } }\r\n"
//
///* =============== LOGIN PAGE =============== */
//".login_page { display:flex; flex-direction:column; align-items:center; justify-content:center; height:100vh; background: linear-gradient(135deg, #0d47a1 0%, #1565c0 100%); }\r\n"
//".login_box { background:#1a237e; padding:40px; border-radius:16px; width:320px; box-shadow:0 8px 32px rgba(0,0,0,0.3); border:1px solid #283593; }\r\n"
//".hidden { display:none; }\r\n"
//".btn { padding:14px 28px; border:none; border-radius:8px; cursor:pointer; background: linear-gradient(135deg, #1976d2 0%, #1565c0 100%); color:white; font-weight:600; font-size:16px; transition: all 0.3s ease; box-shadow: 0 4px 15px rgba(25, 118, 210, 0.4); animation: fadeInUp 0.8s ease 0.6s both; }\r\n"
//".btn:hover { background: linear-gradient(135deg, #1565c0 0%, #0d47a1 100%); transform: translateY(-2px); box-shadow: 0 6px 20px rgba(25, 118, 210, 0.5); }\r\n"
//".btn:active { transform: translateY(0); }\r\n"
//"select, input { border:1px solid #283593; border-radius:8px; background:#0d47a1; color:#e3f2fd; padding:12px; font-size:14px; transition: all 0.3s ease; }\r\n"
//"select:focus, input:focus { outline:none; border-color:#42a5f5; box-shadow: 0 0 0 3px rgba(66, 165, 245, 0.1); }\r\n"
//
///* =============== ADMIN PANEL =============== */
//".admin_container { padding:40px; background: linear-gradient(135deg, #0a1929 0%, #0d47a1 100%); min-height:100vh; }\r\n"
//".admin_header { margin-bottom:40px; }\r\n"
//".admin_title { color:#ffffff; font-size:36px; margin-bottom:10px; font-weight:700; }\r\n"
//".admin_subtitle { color:#90caf9; font-size:16px; font-weight:400; }\r\n"
//".stats_grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(250px, 1fr)); gap:24px; margin-bottom:40px; }\r\n"
//".stat_card { background: linear-gradient(135deg, #1565c0 0%, #0d47a1 100%); padding:24px; border-radius:12px; box-shadow:0 4px 20px rgba(0,0,0,0.2); border:1px solid #1976d2; cursor:pointer; transition: all 0.3s ease; }\r\n"
//".stat_card:hover { transform: translateY(-5px); box-shadow:0 8px 30px rgba(25, 118, 210, 0.4); border-color:#42a5f5; }\r\n"
//".stat_icon { font-size:36px; margin-bottom:12px; }\r\n"
//".stat_value { font-size:32px; font-weight:700; color:#ffffff; margin-bottom:8px; }\r\n"
//".stat_label { font-size:14px; color:#90caf9; text-transform:uppercase; letter-spacing:1px; }\r\n"
//
///* =============== HISTORY SECTION =============== */
//".historyBox { background: linear-gradient(135deg, #1a237e 0%, #0d47a1 100%); border:1px solid #283593; border-radius:12px; padding:30px; box-shadow:0 4px 20px rgba(0,0,0,0.2); }\r\n"
//".histTitle { font-size:24px; font-weight:600; color:#ffffff; margin-bottom:24px; border-bottom:2px solid #1976d2; padding-bottom:12px; }\r\n"
//".history_grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(300px, 1fr)); gap:20px; }\r\n"
//".histCard { background:#0d47a1; padding:20px; border-radius:10px; border:1px solid #1565c0; cursor:pointer; transition: all 0.3s ease; box-shadow:0 2px 10px rgba(0,0,0,0.15); }\r\n"
//".histCard:hover { transform: translateY(-3px); box-shadow:0 6px 25px rgba(25, 118, 210, 0.3); border-color:#42a5f5; background:#1565c0; }\r\n"
//".histDevice { font-size:18px; font-weight:600; color:#ffffff; margin-bottom:8px; }\r\n"
//".histDate { font-size:13px; color:#90caf9; margin-bottom:10px; }\r\n"
//".histDesc { font-size:14px; color:#bbdefb; line-height:1.5; }\r\n"
//
///* =============== OPERATOR PAGE =============== */
//".header_back, .footer_back { background: linear-gradient(135deg, #0d47a1 0%, #1565c0 100%); }\r\n"
//".content_back { background:#0a1929; }\r\n"
//".title { color:#ffffff; font-weight:600; }\r\n"
//".comment { color:#90caf9; font-weight:500; }\r\n"
//"label { color:#90caf9; font-size:13px; font-weight:500; text-transform:uppercase; letter-spacing:0.5px; }\r\n"
//"h3 { margin-top:0; }\r\n"
//"</style>\r\n"
//
//"<script>\r\n"
//"function goToLogin(){ document.getElementById('welcome').classList.add('hidden'); document.getElementById('login').classList.remove('hidden'); }\r\n"
//
//"function loginSubmit(){\r\n"
//"  var role = document.getElementById('role').value;\r\n"
//"  var pass = document.getElementById('password').value;\r\n"
//"  if(role==='admin' && pass==='admin123'){\r\n"
//"     document.getElementById('login').classList.add('hidden');\r\n"
//"     document.getElementById('adminPanel').classList.remove('hidden');\r\n"
//"  }\r\n"
//"  else if(role==='operator' && pass==='operator123'){\r\n"
//"     document.getElementById('login').classList.add('hidden');\r\n"
//"     document.getElementById('operatorPage').classList.remove('hidden');\r\n"
//"  }\r\n"
//"  else{ alert('Invalid Credentials'); }\r\n"
//"}\r\n"
//"</script>\r\n"
//
//"</head>\r\n"
//"<body>\r\n"
//
///* ------------------------ WELCOME PAGE ------------------------ */
//"<div id='welcome' class='welcome_page'>\r\n"
//"<div class='welcome_content'>\r\n"
//"<div class='welcome_icon'>🔷</div>\r\n"
//"<div class='welcome_title'>Excellent Solutions</div>\r\n"
//"<div class='welcome_subtitle'>Professional Device Management System</div>\r\n"
//"<button class='btn' onclick='goToLogin()'>Get Started</button>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//
///* ------------------------ LOGIN PAGE ------------------------ */
//"<div id='login' class='login_page hidden'>\r\n"
//"<div class='login_box'>\r\n"
//"<h3 style='text-align:center; color:#ffffff; font-size:26px; margin-bottom:30px;'>Sign In</h3>\r\n"
//"<label>Role:</label>\r\n"
//"<select id='role' style='width:100%; margin-top:8px;'>\r\n"
//"<option value='operator'>Operator</option>\r\n"
//"<option value='admin'>Admin</option>\r\n"
//"</select><br><br>\r\n"
//
//"<label>Password:</label>\r\n"
//"<input id='password' type='password' style='width:100%; margin-top:8px;'><br><br><br>\r\n"
//
//"<button class='btn' style='width:100%;' onclick='loginSubmit()'>Login</button>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//
///* ------------------------ ADMIN PANEL ------------------------ */
//"<div id='adminPanel' class='hidden admin_container'>\r\n"
//"<div class='admin_header'>\r\n"
//"<div class='admin_title'>Admin Dashboard</div>\r\n"
//"<div class='admin_subtitle'>Complete system overview and management</div>\r\n"
//"</div>\r\n"
//
///* Stats Cards Grid */
//"<div class='stats_grid'>\r\n"
//"<div class='stat_card'>\r\n"
//"<div class='stat_icon'>📊</div>\r\n"
//"<div class='stat_value'>24</div>\r\n"
//"<div class='stat_label'>Active Devices</div>\r\n"
//"</div>\r\n"
//"<div class='stat_card'>\r\n"
//"<div class='stat_icon'>📁</div>\r\n"
//"<div class='stat_value'>156</div>\r\n"
//"<div class='stat_label'>Total Uploads</div>\r\n"
//"</div>\r\n"
//"<div class='stat_card'>\r\n"
//"<div class='stat_icon'>👥</div>\r\n"
//"<div class='stat_value'>8</div>\r\n"
//"<div class='stat_label'>Active Users</div>\r\n"
//"</div>\r\n"
//"<div class='stat_card'>\r\n"
//"<div class='stat_icon'>⚙️</div>\r\n"
//"<div class='stat_value'>99.8%</div>\r\n"
//"<div class='stat_label'>System Uptime</div>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//
///* History Section with Cards */
//"<div class='historyBox'>\r\n"
//"<div class='histTitle'>📋 Recent Activity History</div>\r\n"
//"<div class='history_grid'>\r\n"
//
//"<div class='histCard'>\r\n"
//"<div class='histDevice'>Device A1</div>\r\n"
//"<div class='histDate'>📅 November 21, 2025</div>\r\n"
//"<div class='histDesc'>Image updated — Face alignment corrected</div>\r\n"
//"</div>\r\n"
//
//"<div class='histCard'>\r\n"
//"<div class='histDevice'>Device B7</div>\r\n"
//"<div class='histDate'>📅 November 18, 2025</div>\r\n"
//"<div class='histDesc'>Uploaded new template — Contrast enhanced</div>\r\n"
//"</div>\r\n"
//
//"<div class='histCard'>\r\n"
//"<div class='histDevice'>Device C3</div>\r\n"
//"<div class='histDate'>📅 November 15, 2025</div>\r\n"
//"<div class='histDesc'>Operator replaced image — Resolution improved</div>\r\n"
//"</div>\r\n"
//
//"<div class='histCard'>\r\n"
//"<div class='histDevice'>Device A1</div>\r\n"
//"<div class='histDate'>📅 November 5, 2025</div>\r\n"
//"<div class='histDesc'>Cropping parameters updated</div>\r\n"
//"</div>\r\n"
//
//"<div class='histCard'>\r\n"
//"<div class='histDevice'>Device D2</div>\r\n"
//"<div class='histDate'>📅 November 1, 2025</div>\r\n"
//"<div class='histDesc'>New logo overlay added</div>\r\n"
//"</div>\r\n"
//
//"</div>\r\n"
//"</div>\r\n"
//
//"</div>\r\n"
//
///* ------------------------ ORIGINAL OPERATOR PAGE ------------------------ */
//"<div id='operatorPage' class='hidden'>\r\n"
//"<div class='header_back'>\r\n"
//"<div class='header_face'></div>\r\n"
//"</div>\r\n"
//"<div class='content_back'>\r\n"
//"<div class='content_face'>\r\n"
//"<table style='width:100%; height:100%' border='0' cellspacing='0'>\r\n"
//"<tr>\r\n"
//"<td class='menu_bar' rowspan='2'>\r\n"
//"<div id='BT'></div>\r\n"
//"<table>\r\n"
//"<tr>\r\n"
//"<td class='comment' colspan='4'><br>Device IP:</td>\r\n"
//"</tr>\r\n"
//"<tr>\r\n"
//"<td colspan='4'><input id='ip_addr' style='width:100%;text-align:center' type='text' value='" +
//String(myIP[0]) + "." + String(myIP[1]) + "." + String(myIP[2]) + "." + String(myIP[3]) +
//"'></td>\r\n"
//"</tr>\r\n"
//"<tr><td class='comment' colspan='4'><br>Bounds:</td></tr>\r\n"
//"<tr id='XY'></tr>\r\n"
//"<tr id='WH'></tr>\r\n"
//"</table>\r\n"
//"<div id='RB'></div>\r\n"
//"</td>\r\n"
//
//"<td class='content_body'>\r\n"
//"<span class='title'>Original image</span><br>\r\n"
//"<canvas id='source' class='hidden_input'></canvas>\r\n"
//"<div id='srcBox'>\r\n"
//"<div class='imgBox'>\r\n"
//"<div class='mesBox'>Drop image here...</div>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//"</td>\r\n"
//"</tr>\r\n"
//
//"<tr>\r\n"
//"<td id='dstBox' class='content_body'>\r\n"
//"</td>\r\n"
//"</tr>\r\n"
//
//"</table>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//
//"<div class='footer_back'>\r\n"
//"<div class='footer_face' id='logTag'>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//
//"</body>\r\n"
//"</html>\r\n"
//);
//}


//
//void sendHtml(WiFiClient client, IPAddress myIP)
//{
//client.print(
//"<!DOCTYPE html>\r\n"
//"<html>\r\n"
//"<head>\r\n"
//"<meta charset='utf-8'>\r\n"
//"<title>Excellent Solutions</title>\r\n"
//"<link rel='icon' href='data:;base64,='>\r\n"
//"<link rel='stylesheet' href='styles.css'>\r\n"
//"<script src='scriptA.js'></script>\r\n"
//"<script src='scriptB.js'></script>\r\n"
//"<script src='scriptC.js'></script>\r\n"
//"<script src='scriptD.js'></script>\r\n"
//
//"<style>\r\n"
//"body { font-family: Arial; margin:0; padding:0; background:#f0f6ff; color:#002b5c; }\r\n"
//".welcome_page, .login_page { display:flex; flex-direction:column; align-items:center; justify-content:center; height:100vh; background:#ffffff; }\r\n"
//".welcome_title { font-size:40px; font-weight:bold; margin-bottom:20px; color:#004aad; }\r\n"
//".login_box { background:white; padding:25px; border-radius:12px; width:300px; box-shadow:0 0 12px rgba(0,60,120,0.2); border:1px solid #d0e2ff; }\r\n"
//".hidden { display:none; }\r\n"
//".btn { padding:10px 18px; border:none; border-radius:6px; cursor:pointer; background:#0066cc; color:white; font-weight:bold; }\r\n"
//".btn:hover { background:#0052a3; }\r\n"
//"select, input { border:1px solid #aac8ff; border-radius:6px; }\r\n"
//".header_back, .footer_back { background:#e6f0ff; }\r\n"
//".content_back { background:#ffffff; }\r\n"
//".title { color:#004aad; font-weight:bold; }\r\n"
//".comment { color:#003366; font-weight:bold; }\r\n"
//"</style>\r\n"
//
//"<script>\r\n"
//"function goToLogin(){ document.getElementById('welcome').classList.add('hidden'); document.getElementById('login').classList.remove('hidden'); }\r\n"
//
//"function loginSubmit(){\r\n"
//"  var role = document.getElementById('role').value;\r\n"
//"  var pass = document.getElementById('password').value;\r\n"
//"  if(role==='admin' && pass==='admin123'){\r\n"
//"     document.getElementById('login').classList.add('hidden');\r\n"
//"     document.getElementById('adminPanel').classList.remove('hidden');\r\n"
//"  }\r\n"
//"  else if(role==='operator' && pass==='operator123'){\r\n"
//"     document.getElementById('login').classList.add('hidden');\r\n"
//"     document.getElementById('operatorPage').classList.remove('hidden');\r\n"
//"  }\r\n"
//"  else{ alert('Invalid Credentials'); }\r\n"
//"}\r\n"
//"</script>\r\n"
//
//"</head>\r\n"
//"<body>\r\n"
//
///* ------------------------ WELCOME PAGE ------------------------ */
//"<div id='welcome' class='welcome_page'>\r\n"
//"<div class='welcome_title'>Welcome to Excellent Solutions</div>\r\n"
//"<button class='btn' onclick='goToLogin()'>Continue</button>\r\n"
//"</div>\r\n"
//
///* ------------------------ LOGIN PAGE ------------------------ */
//"<div id='login' class='login_page hidden'>\r\n"
//"<div class='login_box'>\r\n"
//"<h3 style='text-align:center; color:#004aad;'>Login</h3>\r\n"
//"<label>Role:</label>\r\n"
//"<select id='role' style='width:100%; padding:6px;'>\r\n"
//"<option value='operator'>Operator</option>\r\n"
//"<option value='admin'>Admin</option>\r\n"
//"</select><br><br>\r\n"
//
//"<label>Password:</label>\r\n"
//"<input id='password' type='password' style='width:100%; padding:6px;'><br><br>\r\n"
//
//"<button class='btn' style='width:100%;' onclick='loginSubmit()'>Login</button>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//
///* ------------------------ ADMIN PANEL ------------------------ */
//"<div id='adminPanel' class='hidden' style='padding:20px;'>\r\n"
//"<h2 style='color:#004aad;'>Admin Dashboard</h2>\r\n"
//"<p>You have full access: device logs, history, last update information, user activity, configuration control, etc.</p>\r\n"
//"<p>(Add your admin HTML here later if needed)</p>\r\n"
//"</div>\r\n"
//
///* ------------------------ ORIGINAL OPERATOR PAGE ------------------------ */
//"<div id='operatorPage' class='hidden'>\r\n"
//"<div class='header_back'>\r\n"
//"<div class='header_face'></div>\r\n"
//"</div>\r\n"
//"<div class='content_back'>\r\n"
//"<div class='content_face'>\r\n"
//"<table style='width:100%; height:100%' border='0' cellspacing='0'>\r\n"
//"<tr>\r\n"
//"<td class='menu_bar' rowspan='2'>\r\n"
//"<div id='BT'></div>\r\n"
//"<table>\r\n"
//"<tr>\r\n"
//"<td class='comment' colspan='4'><br>Device IP:</td>\r\n"
//"</tr>\r\n"
//"<tr>\r\n"
//"<td colspan='4'><input id='ip_addr' style='width:100%;text-align:center' type='text' value='" +
//String(myIP[0]) + "." + String(myIP[1]) + "." + String(myIP[2]) + "." + String(myIP[3]) +
//"'></td>\r\n"
//"</tr>\r\n"
//"<tr><td class='comment' colspan='4'><br>Bounds:</td></tr>\r\n"
//"<tr id='XY'></tr>\r\n"
//"<tr id='WH'></tr>\r\n"
//"</table>\r\n"
//"<div id='RB'></div>\r\n"
//"</td>\r\n"
//
//"<td class='content_body'>\r\n"
//"<span class='title'>Original image</span><br>\r\n"
//"<canvas id='source' class='hidden_input'></canvas>\r\n"
//"<div id='srcBox'>\r\n"
//"<div class='imgBox'>\r\n"
//"<div class='mesBox'>Drop image here...</div>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//"</td>\r\n"
//"</tr>\r\n"
//
//"<tr>\r\n"
//"<td id='dstBox' class='content_body'>\r\n"
//"</td>\r\n"
//"</tr>\r\n"
//
//"</table>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//
//"<div class='footer_back'>\r\n"
//"<div class='footer_face' id='logTag'>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//"</div>\r\n"
//
//"</body>\r\n"
//"</html>\r\n"
//);
//}
//
